from django.db import models

class HkPacket(models.Model):
    Filename = models.CharField(max_length=100)
    CCSDSVER = models.CharField(max_length=200)
    CCSDSTYPE = models.CharField(max_length=200)
    CCSDSSHF = models.CharField(max_length=200)
    CCSDSAPID = models.CharField(max_length=200)
    CCSDSSEQFLAGS = models.CharField(max_length=200)
    CCSDSSEQCNT = models.CharField(max_length=200)
    CCSDSLENGTH = models.CharField(max_length=200)
    SHCOARSE = models.CharField(max_length=200)
    SHFINE = models.CharField(max_length=200)
    Cmd_ADF_Counts  = models.CharField(max_length=200)
    Cmd_RS485_Succ_Counts = models.CharField(max_length=200)
    Cmd_RS485_Fail_Counts = models.CharField(max_length=200)
    Image_ID = models.CharField(max_length=200)
    CLK_Rate = models.CharField(max_length=200)
    Command_Loss_Timer = models.CharField(max_length=200)
    Prev_CMD_Receive = models.CharField(max_length=200)
    Latest_CodeWord_RCV = models.CharField(max_length=200)
    Reset_Counts = models.CharField(max_length=200)
    RTM = models.CharField(max_length=200)
    Acceleration = models.CharField(max_length=200)
    Angular_Rate = models.CharField(max_length=200)
    IMU_Temp = models.CharField(max_length=200)
    Voltage = models.CharField(max_length=200)
    Current = models.CharField(max_length=200)
    HK_Read_Pointer = models.CharField(max_length=200)
    HK_Write_Pointer = models.CharField(max_length=200)
    Thermistor_Read_Pointer  = models.CharField(max_length=200)
    Thermistor_Write_Pointer  = models.CharField(max_length=200)
    Comms_Read_Pointer = models.CharField(max_length=200)
    Comms_Write_Pointer = models.CharField(max_length=200)
    sd_dump = models.CharField(max_length=200)
    GPS_Time_State_Vector = models.CharField(max_length=200)
    Fletcher_Code = models.CharField(max_length=200)

class GmcPacket(models.Model):
    Filename = models.CharField(max_length=100)
    CCSDSVER = models.CharField(max_length=200)
    CCSDSTYPE = models.CharField(max_length=200)
    CCSDSSHF = models.CharField(max_length=200)
    CCSDSAPID = models.CharField(max_length=200)
    CCSDSSEQFLAGS = models.CharField(max_length=200)
    CCSDSSEQCNT = models.CharField(max_length=200)
    CCSDSLENGTH = models.CharField(max_length=200)
    SHCOARSE = models.CharField(max_length=200)
    SHFINE = models.CharField(max_length=200)
    Image_ID = models.CharField(max_length=200)
    GMC_Radiation_Counts = models.CharField(max_length=200)
    GMC_Read_Free_Register = models.CharField(max_length=200)
    GMC_Test_Voltage_ADC = models.CharField(max_length=200)
    GMC_sd_dump = models.CharField(max_length=200)
    GPS_Time_State_Vector = models.CharField(max_length=200)
    Fletcher_Code = models.CharField(max_length=200)

class CommsPacket(models.Model):
    Filename = models.CharField(max_length=100)
    CCSDSVER = models.CharField(max_length=200)
    CCSDSTYPE = models.CharField(max_length=200)
    CCSDSSHF = models.CharField(max_length=200)
    CCSDSAPID = models.CharField(max_length=200)
    CCSDSSEQFLAGS = models.CharField(max_length=200)
    CCSDSSEQCNT = models.CharField(max_length=200)
    CCSDSLENGTH = models.CharField(max_length=200)
    SHCOARSE = models.CharField(max_length=200)
    SHFINE = models.CharField(max_length=200)
    Image_ID = models.CharField(max_length=200)
    Comms_ADF_CMD_Rx = models.CharField(max_length=200)
    Comms_ADF_CMD_Succ = models.CharField(max_length=200)
    Comms_ADF_CMD_REJECT = models.CharField(max_length=200)
    Comms_ADF_RSSI_CCA = models.CharField(max_length=200)
    Comms_ADF_RSSI = models.CharField(max_length=200)
    Comms_ADF_Preamble_Pattern = models.CharField(max_length=200)
    Comms_ADF_Sync_Word = models.CharField(max_length=200)
    Comms_ADF_Freq = models.CharField(max_length=200)
    Comms_ADF_Read_REG_ADDR = models.CharField(max_length=200)
    Comms_ADF_Read_REG_No_Double_Words = models.CharField(max_length=200)
    Comms_ADF_Data = models.CharField(max_length=200)
    Comms_ADF_State = models.CharField(max_length=200)
    sd_dump = models.CharField(max_length=200)
    GPS_Time_State_Vector = models.CharField(max_length=200)
    Fletcher_Code = models.CharField(max_length=200)

class TempPacket(models.Model):
    Filename = models.CharField(max_length=100)
    CCSDSVER = models.CharField(max_length=200)
    CCSDSTYPE = models.CharField(max_length=200)
    CCSDSSHF = models.CharField(max_length=200)
    CCSDSAPID = models.CharField(max_length=200)
    CCSDSSEQFLAGS = models.CharField(max_length=200)
    CCSDSSEQCNT = models.CharField(max_length=200)
    CCSDSLENGTH = models.CharField(max_length=200)
    SHCOARSE = models.CharField(max_length=200)
    SHFINE = models.CharField(max_length=200)
    Temperature_Values = models.CharField(max_length=200)
    sd_dump = models.CharField(max_length=200)
    GPS_Time_State_Vector = models.CharField(max_length=200)
    Fletcher_Code = models.CharField(max_length=200)

class InitPacket(models.Model):
    Filename = models.CharField(max_length=100)
    CCSDSVER = models.CharField(max_length=200)
    CCSDSTYPE = models.CharField(max_length=200)
    CCSDSSHF = models.CharField(max_length=200)
    CCSDSAPID = models.CharField(max_length=200)
    CCSDSSEQFLAGS = models.CharField(max_length=200)
    CCSDSSEQCNT = models.CharField(max_length=200)
    CCSDSLENGTH = models.CharField(max_length=200)
    SHCOARSE = models.CharField(max_length=200)
    SHFINE = models.CharField(max_length=200)
    Image_ID = models.CharField(max_length=200)
    status = models.CharField(max_length=200)
    ADF_Init = models.CharField(max_length=200)
    config = models.CharField(max_length=200)
    GPS_Time_State_Vector = models.CharField(max_length=200)
    Fletcher_Code = models.CharField(max_length=200)

