from django.db import models

class HkPacket(models.Model):
    Filename = models.CharField(max_length=100)
    Cmd_ADF_Counts  = models.IntegerField()
    Cmd_RS485_Succ_Counts = models.IntegerField()
    Cmd_RS485_Fail_Counts = models.IntegerField()
    Image_ID = models.IntegerField()
    CLK_Rate = models.IntegerField()
    Command_Loss_Timer = models.IntegerField()
    Prev_CMD_Receive = models.IntegerField()
    Latest_CodeWord_RCV = models.IntegerField()
    Reset_Counts = models.IntegerField()
    RTM = models.IntegerField()
    Acceleration = models.IntegerField()
    Angular_Rate = models.IntegerField()
    IMU_Temp = models.IntegerField()
    Voltage = models.IntegerField()
    Current = models.IntegerField()
    HK_Read_Pointer = models.IntegerField()
    HK_Write_Pointer = models.IntegerField()
    Thermistor_Read_Pointer  = models.IntegerField()
    Thermistor_Write_Pointer  = models.IntegerField()
    Comms_Read_Pointer = models.IntegerField()
    Comms_Write_Pointer = models.IntegerField()
    sd_dump = models.IntegerField()
    GPS_Time_State_Vector = models.IntegerField()
    Fletcher_Code = models.IntegerField()

class GmcPacket(models.Model):
    Filename = models.CharField(max_length=100)
    Image_ID = models.IntegerField()
    GMC_Radiation_Counts = models.IntegerField()
    GMC_Read_Free_Register = models.IntegerField()
    GMC_Test_Voltage_ADC = models.IntegerField()
    GMC_sd_dump = models.IntegerField()
    GPS_Time_State_Vector = models.IntegerField()
    Fletcher_Code = models.IntegerField()

class CommsPacket(models.Model):
    Filename = models.CharField(max_length=100)
    Image_ID = models.IntegerField()
    Comms_ADF_CMD_Rx = models.IntegerField()
    Comms_ADF_CMD_Succ = models.IntegerField()
    Comms_ADF_CMD_REJECT = models.IntegerField()
    Comms_ADF_RSSI_CCA = models.IntegerField()
    Comms_ADF_RSSI = models.IntegerField()
    Comms_ADF_Preamble_Pattern = models.IntegerField()
    Comms_ADF_Sync_Word = models.IntegerField()
    Comms_ADF_Freq = models.IntegerField()
    Comms_ADF_Read_REG_ADDR = models.IntegerField()
    Comms_ADF_Read_REG_No_Double_Words = models.IntegerField()
    Comms_ADF_Data = models.IntegerField()
    Comms_ADF_State = models.IntegerField()
    sd_dump = models.IntegerField()
    GPS_Time_State_Vector = models.IntegerField()
    Fletcher_Code = models.IntegerField()

class TempPacket(models.Model):
    Filename = models.CharField(max_length=100)
    Temperature_Values = models.IntegerField()
    sd_dump = models.IntegerField()
    GPS_Time_State_Vector = models.IntegerField()
    Fletcher_Code = models.IntegerField()

class InitPacket(models.Model):
    Filename = models.CharField(max_length=100)
    Image_ID = models.IntegerField()
    status = models.IntegerField()
    ADF_Init = models.IntegerField()
    config = models.IntegerField()
    GPS_Time_State_Vector = models.IntegerField()
    Fletcher_Code = models.IntegerField()

